name: mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true

  assets:
    - assets/images/promote_one.png
    - assets/images/promote_two.png
    - assets/images/promote_three.png
    - assets/images/back_tab.png
    - assets/images/sneaker_options_one.png
    - assets/images/sneaker_options_two.png
    - assets/images/sneaker_options_three.png
    - assets/images/sneaker_options_four.png
    - assets/images/nike_homem_aranha/background.png
    - assets/images/nike_homem_aranha/sneaker_one.png
    - assets/images/nike_homem_aranha/sneaker_two.png
    - assets/images/nike_homem_aranha/sneaker_three.png
    - assets/images/nike_homem_aranha/thumbnail.png
    - assets/images/nike_air_max_520/background.png
    - assets/images/nike_air_max_520/sneaker_one.png
    - assets/images/nike_air_max_520/sneaker_two.png
    - assets/images/nike_air_max_520/sneaker_three.png    
    - assets/images/nike_air_max_520/thumbnail.png    
    - assets/images/nike_caminhada/background.png
    - assets/images/nike_caminhada/sneaker_one.png
    - assets/images/nike_caminhada/sneaker_two.png
    - assets/images/nike_caminhada/sneaker_three.png    
    - assets/images/nike_caminhada/thumbnail.png    
    - assets/images/nike_flywire_force_1/background.png
    - assets/images/nike_flywire_force_1/sneaker_one.png
    - assets/images/nike_flywire_force_1/sneaker_two.png
    - assets/images/nike_flywire_force_1/sneaker_three.png
    - assets/images/nike_flywire_force_1/thumbnail.png
      
    - assets/images/nike_air_max_aquaman/background.png
    - assets/images/nike_air_max_aquaman/sneaker_one.png
    - assets/images/nike_air_max_aquaman/sneaker_two.png
    - assets/images/nike_air_max_aquaman/sneaker_three.png
    - assets/images/nike_air_max_aquaman/thumbnail.png
      
    - assets/images/nike_caminhada_matinal/background.png
    - assets/images/nike_caminhada_matinal/sneaker_one.png
    - assets/images/nike_caminhada_matinal/sneaker_two.png
    - assets/images/nike_caminhada_matinal/sneaker_three.png
    - assets/images/nike_caminhada_matinal/thumbnail.png
    
  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
        - asset: assets/fonts/Heebo-Medium.ttf
        - asset: assets/fonts/Heebo-Regular.ttf
        - asset: assets/fonts/Heebo-SemiBold.ttf
          weight: 700
